model = "gpt-5.1-codex"
model_reasoning_effort = "high"

[projects."/Users/nekobato/my/nekobato/asmr-voice"]
trust_level = "trusted"

[projects."/Users/nekobato/my/nekobato/cms"]
trust_level = "trusted"

[projects."/Users/nekobato/my/nekobato/blopon"]
trust_level = "trusted"

[projects."/Users/nekobato/my/nekobato/auth-base"]
trust_level = "trusted"

[projects."/Users/nekobato/my/rabo/rabo-corporate"]
trust_level = "trusted"

[projects."/Users/nekobato/my/nekobato/strapi-custom-example"]
trust_level = "trusted"

[projects."/Users/nekobato/my/rabo/rabo-web-cms-strapi"]
trust_level = "trusted"

[features]
web_search_request = true

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest"]

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp", "--api-key", "ctx7sk-aa23f169-d05f-45bc-9ffb-1de5ea27c5cc"]
